/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplashRouteImport } from './routes/_splash'
import { Route as PreviewRouteRouteImport } from './routes/preview/route'
import { Route as SplashIndexRouteRouteImport } from './routes/_splash/index/route'
import { Route as GameRoomIdPlayRouteRouteImport } from './routes/game/$roomId/play/route'
import { Route as GameRoomIdLobbyRouteRouteImport } from './routes/game/$roomId/lobby/route'
import { Route as SplashGameCreateRouteRouteImport } from './routes/_splash/game/create/route'

const SplashRoute = SplashRouteImport.update({
  id: '/_splash',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRouteRoute = PreviewRouteRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashIndexRouteRoute = SplashIndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => SplashRoute,
} as any)
const GameRoomIdPlayRouteRoute = GameRoomIdPlayRouteRouteImport.update({
  id: '/game/$roomId/play',
  path: '/game/$roomId/play',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoomIdLobbyRouteRoute = GameRoomIdLobbyRouteRouteImport.update({
  id: '/game/$roomId/lobby',
  path: '/game/$roomId/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashGameCreateRouteRoute = SplashGameCreateRouteRouteImport.update({
  id: '/game/create',
  path: '/game/create',
  getParentRoute: () => SplashRoute,
} as any)

export interface FileRoutesByFullPath {
  '/preview': typeof PreviewRouteRoute
  '/': typeof SplashIndexRouteRoute
  '/game/create': typeof SplashGameCreateRouteRoute
  '/game/$roomId/lobby': typeof GameRoomIdLobbyRouteRoute
  '/game/$roomId/play': typeof GameRoomIdPlayRouteRoute
}
export interface FileRoutesByTo {
  '/preview': typeof PreviewRouteRoute
  '/': typeof SplashIndexRouteRoute
  '/game/create': typeof SplashGameCreateRouteRoute
  '/game/$roomId/lobby': typeof GameRoomIdLobbyRouteRoute
  '/game/$roomId/play': typeof GameRoomIdPlayRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/preview': typeof PreviewRouteRoute
  '/_splash': typeof SplashRouteWithChildren
  '/_splash/': typeof SplashIndexRouteRoute
  '/_splash/game/create': typeof SplashGameCreateRouteRoute
  '/game/$roomId/lobby': typeof GameRoomIdLobbyRouteRoute
  '/game/$roomId/play': typeof GameRoomIdPlayRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/preview'
    | '/'
    | '/game/create'
    | '/game/$roomId/lobby'
    | '/game/$roomId/play'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/preview'
    | '/'
    | '/game/create'
    | '/game/$roomId/lobby'
    | '/game/$roomId/play'
  id:
    | '__root__'
    | '/preview'
    | '/_splash'
    | '/_splash/'
    | '/_splash/game/create'
    | '/game/$roomId/lobby'
    | '/game/$roomId/play'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PreviewRouteRoute: typeof PreviewRouteRoute
  SplashRoute: typeof SplashRouteWithChildren
  GameRoomIdLobbyRouteRoute: typeof GameRoomIdLobbyRouteRoute
  GameRoomIdPlayRouteRoute: typeof GameRoomIdPlayRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_splash': {
      id: '/_splash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_splash/': {
      id: '/_splash/'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SplashIndexRouteRouteImport
      parentRoute: typeof SplashRoute
    }
    '/game/$roomId/play': {
      id: '/game/$roomId/play'
      path: '/game/$roomId/play'
      fullPath: '/game/$roomId/play'
      preLoaderRoute: typeof GameRoomIdPlayRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$roomId/lobby': {
      id: '/game/$roomId/lobby'
      path: '/game/$roomId/lobby'
      fullPath: '/game/$roomId/lobby'
      preLoaderRoute: typeof GameRoomIdLobbyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_splash/game/create': {
      id: '/_splash/game/create'
      path: '/game/create'
      fullPath: '/game/create'
      preLoaderRoute: typeof SplashGameCreateRouteRouteImport
      parentRoute: typeof SplashRoute
    }
  }
}

interface SplashRouteChildren {
  SplashIndexRouteRoute: typeof SplashIndexRouteRoute
  SplashGameCreateRouteRoute: typeof SplashGameCreateRouteRoute
}

const SplashRouteChildren: SplashRouteChildren = {
  SplashIndexRouteRoute: SplashIndexRouteRoute,
  SplashGameCreateRouteRoute: SplashGameCreateRouteRoute,
}

const SplashRouteWithChildren =
  SplashRoute._addFileChildren(SplashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PreviewRouteRoute: PreviewRouteRoute,
  SplashRoute: SplashRouteWithChildren,
  GameRoomIdLobbyRouteRoute: GameRoomIdLobbyRouteRoute,
  GameRoomIdPlayRouteRoute: GameRoomIdPlayRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
