/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// This file is auto-generated by TanStack Router on first `bun dev:web`

import { createRootRoute } from "@tanstack/react-router";

const rootRoute = createRootRoute();

export const routeTree = rootRoute;
